#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# create folders
mkdir -p \
    /config/ \
    /var/cache/smokeping \
    /data

# copy config files

PREV_DIR=$(pwd)

cd /defaults/smoke-conf || exit
shopt -s globstar nullglob
for i in *; do
    if [[ ! -e "/config/${i}" ]]; then
        cp -v "${i}" "/config/${i}"
    fi
done

cd "${PREV_DIR}" || exit

if [[ -e /config/ssmtp.conf ]]; then
    cp /config/ssmtp.conf /etc/ssmtp/ssmtp.conf
fi

if [[ ! -f /usr/bin/tcpping ]]; then
    install -m755 -D /defaults/tcpping /usr/bin/
fi

# permissions
chmod 777 /var/cache/fontconfig/

lsiown -R abc:abc \
    /config \
    /data \
    /run/apache2 \
    /usr/share/webapps/smokeping \
    /var/cache/smokeping \
    /var/www/localhost/smokeping
