#!/usr/bin/with-contenv bash
# shellcheck shell=bash

exec \
     s6-setuidgid abc /usr/sbin/smokeping --master-url=http://smokeping-master/smokeping/smokeping.cgi --slave-name=slave --shared-secret=/config/slave_secrets --cache-dir=/var/cache/smokeping/ --nodaemon

